[font.normal]
family = "FiraCode Nerd Font"


[keyboard]
bindings = [
	{ key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "F11", action = "ToggleFullscreen" },
	{ key = "Enter", mods = "Control", action = "ToggleFullscreen" },
]

[window]
opacity = 0.89

[general]
import = [
	"/home/jimit/.config/alacritty/themes/one_dark.toml"
]
