[language-server.rust-analyzer]
command = "rust-analyzer"
args = []

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.vscode-html-languageserver]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.marksman]
command = "marksman"

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "cargo fmt" }

[[language]]
name = "javascript"
injection-regex = "html"
file-types = ["js"]
auto-format = true
comment-token = "//"
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx prettier", args = ["--write --use-tabs"] }

[[language]]
name = "typescript"
injection-regex = "html"
file-types = ["ts"]
auto-format = true
comment-token = "//"
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx prettier", args = ["--write --use-tabs"] }

[[language]]
name = "jsx"
injection-regex = "html"
file-types = ["jsx"]
auto-format = true
comment-token = "//"
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx prettier", args = ["--write --use-tabs"] }

[[language]]
name = "tsx"
injection-regex = "html"
file-types = ["ts"]
auto-format = true
comment-token = "//"
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx prettier", args = ["--write --use-tabs"] }

[[language]]
name = "html"
file-types = ["html", "htm"]
comment-token = "<!-- -->"
language-servers = [ "vscode-html-languageserver" ]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = [ "marksman" ]
indent = { tab-width = 4, unit = "\t" }
